receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

processors:
  resourcedetection:
    detectors: [env, system]
  batch:

exporters:
  # otlp:
  #   endpoint: localhost:4317
  # Data sources: traces, metrics
  otlphttp:
    endpoint: http://localhost:4318

service: 

  pipelines:

    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [otlphttp]